/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as AgentesSlugRouteImport } from './routes/agentes.$slug'
import { Route as ApiHermesCommandsRouteImport } from './routes/api/hermes/commands'
import { Route as ApiPublicHermesHeartbeatRouteImport } from './routes/api/public/hermes/heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesSlugRoute = AgentesSlugRouteImport.update({
  id: '/agentes/$slug',
  path: '/agentes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesCommandsRoute = ApiHermesCommandsRouteImport.update({
  id: '/api/hermes/commands',
  path: '/api/hermes/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHermesHeartbeatRoute =
  ApiPublicHermesHeartbeatRouteImport.update({
    id: '/api/public/hermes/heartbeat',
    path: '/api/public/hermes/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mapa': typeof MapaRoute
  '/agentes/$slug': typeof AgentesSlugRoute
  '/api/hermes/commands': typeof ApiHermesCommandsRoute
  '/api/public/hermes/heartbeat': typeof ApiPublicHermesHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mapa': typeof MapaRoute
  '/agentes/$slug': typeof AgentesSlugRoute
  '/api/hermes/commands': typeof ApiHermesCommandsRoute
  '/api/public/hermes/heartbeat': typeof ApiPublicHermesHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mapa': typeof MapaRoute
  '/agentes/$slug': typeof AgentesSlugRoute
  '/api/hermes/commands': typeof ApiHermesCommandsRoute
  '/api/public/hermes/heartbeat': typeof ApiPublicHermesHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mapa'
    | '/agentes/$slug'
    | '/api/hermes/commands'
    | '/api/public/hermes/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mapa'
    | '/agentes/$slug'
    | '/api/hermes/commands'
    | '/api/public/hermes/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mapa'
    | '/agentes/$slug'
    | '/api/hermes/commands'
    | '/api/public/hermes/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MapaRoute: typeof MapaRoute
  AgentesSlugRoute: typeof AgentesSlugRoute
  ApiHermesCommandsRoute: typeof ApiHermesCommandsRoute
  ApiPublicHermesHeartbeatRoute: typeof ApiPublicHermesHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes/$slug': {
      id: '/agentes/$slug'
      path: '/agentes/$slug'
      fullPath: '/agentes/$slug'
      preLoaderRoute: typeof AgentesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/commands': {
      id: '/api/hermes/commands'
      path: '/api/hermes/commands'
      fullPath: '/api/hermes/commands'
      preLoaderRoute: typeof ApiHermesCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/heartbeat': {
      id: '/api/public/hermes/heartbeat'
      path: '/api/public/hermes/heartbeat'
      fullPath: '/api/public/hermes/heartbeat'
      preLoaderRoute: typeof ApiPublicHermesHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MapaRoute: MapaRoute,
  AgentesSlugRoute: AgentesSlugRoute,
  ApiHermesCommandsRoute: ApiHermesCommandsRoute,
  ApiPublicHermesHeartbeatRoute: ApiPublicHermesHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
